### ISSUE TITLE
Add synpsis & cover to the details page of each TV show

### ISSUE THREAD

**Issue by rmallols** [rmallols/kodflix#16]
We're already displaying the TV show title on the details page of each TV show.

Let's add now the synopsis and the cover. It's also a good opportunity to keep improving our UI, so please play around with background & font colors, gutters, etc

E.g.
![image](https://user-images.githubusercontent.com/264750/41424291-82ca29a8-6ff5-11e8-937d-d390aaf0d414.png)

Bonus: Please look after the mobile layout!
![image](https://user-images.githubusercontent.com/264750/41424449-fa3ab796-6ff5-11e8-81ca-f54184308ba2.png)

**Comment by rmallols** [comment]
**Technical guidance:**

1. Add a `synopsis` attribute to each entry on the list of shows. Fill them with some relevant info.

2. Display the `synopsis` (left) and `image` (right) on the `Details` component, following `flexbox` guidelines:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

3. Re-arrange the layout for mobile, using `media queries` e.g. by simply switching from `display: flex` to `display: block`
https://www.w3schools.com/Css/css_rwd_mediaqueries.asp
You can also add some gutters:
https://www.w3schools.com/cssref/pr_padding.asp

4. On the main CSS file (`App.css`) set a generic font and background colour
https://www.w3schools.com/cssref/pr_text_color.asp
https://www.w3schools.com/cssref/pr_text_color.asp

**Comment by tishayaem** [comment]
Typo in the title. Synpsis => Synopsis
