### ISSUE TITLE
Deploy kodflix to production!

### ISSUE THREAD

**Issue by rmallols** [rmallols/kodflix#17]
Historically speaking, all the feedback we've received came from our internal / beta customers.

They're quite happy with the current state of the art, so now it's time to make `kodflix` publicly available!

That would imply we'll have a public URL access, so everybody around the world could check it.

**Comment by rmallols** [comment]
**Technical guidance:**

We'll deploy our applications to the cloud using `Heroku`
www.heroku.com

It's a very popular framework, with really nice docs and extensive community support.

On top of that, it's free for personal projects, with some limitations (e.g. apps tend to 'sleep', which means first time you access it after a period of inactivity, it'll take few seconds to respond).

Setup process will just take few minutes.

1. Sign up on Heroku: https://signup.heroku.com/
2. Follow the getting started guide until the `Deploy the app` step https://devcenter.heroku.com/articles/getting-started-with-nodejs

**Comment by rmallols** [comment]
The sample app has been already deployed:
https://kodflix.herokuapp.com/

**Comment by zoltanalmodo** [comment]
https://zoltan-kodflix-ddisco-app.herokuapp.com/
app-deployed-in-production
