### ISSUE TITLE
Connect the frontend and backend servers

### ISSUE THREAD

**Issue by rmallols** [rmallols/kodflix#22]
Right, let's start calling the backend server from the frontend.

Please prove we can retrieve the list of TV shows on the frontend from the backend

**Comment by rmallols** [comment]
**Technical guidance:**

1. Due to security reasons, to enable requests from a given url to a different one (in our case, `http://localhost:3000` -> http://localhost:3001).

[We can do that by enabling a proxy from the frontend to the backend](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development).

2. Next, restart the server and call `/rest/shows` from the frontend [using fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

3. You can then display the list of tv shows on the network tab. You can also display them in the devTools console, [using console.log](https://www.w3schools.com/jsref/met_console_log.asp).

![image](https://user-images.githubusercontent.com/264750/41607371-d0f0ef0e-73dd-11e8-9e80-cbbc5d0d4690.png)

**Comment by justinliu6165** [comment]
This video really helped me understand how to use the fetch method 
https://www.youtube.com/watch?v=v0t42xBIYIs
