### ISSUE TITLE
Install a local database

### ISSUE THREAD

**Issue by rmallols** [rmallols/kodflix#26]
We've recently moved our data from the frontend to the backend. That's nice, but could we:
* Filter TV shows (to e.g. just return just a specific one rather than 'all').
* Update content seamlessly (without having to release every time we change something with `git push heroku master`.
* Backup data.

Of course, we could add some tricks to our backend to workaround all these things, but let's not reinvent the wheel and us a proper enterprise-level database: [MongoDB](https://www.mongodb.com/download-center?#community). We'll use it because it comes with a free version, plays really well on the cloud and has a large community support.

The goal of this task is ensuring we can install the database engine locally, so we can integrate it with our app afterwards.

**Comment by rmallols** [comment]
**Technical guidance:**

1. [Install MongoDB locally for your OS](https://www.mongodb.com/download-center?#community). Prove everything is OK by just typing `mongo --version` on a terminal:
![image](https://user-images.githubusercontent.com/264750/41653653-a4f6b1ee-747e-11e8-9337-9dff0a7c216f.png)

2. Start the mongo server, just running `mongod`:
![image](https://user-images.githubusercontent.com/264750/41653695-d1e573c0-747e-11e8-9ef1-1c70941553f7.png)

3. Let's setup our database. On a new terminal tab, type `mongo` to enter the mongo world. And then:
* Create a `kodflix` database: `use kodflix`
* Create a `kodflix` user, with `kodflix` password on that database: `db.createUser({ user: 'kodflix', pwd: 'kodflix', roles: [ "readWrite", "dbAdmin" ] })`

4. At this point, we got the engine running, but it'd be convenient to have a proper UI app to handle our data. Please download [Robo 3T](https://robomongo.org/download). We'll trust it because of its stability and intuitive user interface - and because it's free. 
* Go to `File -> Connect...` and then click on `Create`
* On the first tab (`Connection`) just type the name of the connection. That's not important, but, for consistency reasons, let's call it `kodflix`. Leave everything else default.
![image](https://user-images.githubusercontent.com/264750/41654297-e9bb6f66-7480-11e8-9c7f-d284dadafb6b.png)
* On the `Authentication` tab, Enable `perform authentication` and type `kodflix` on
    * Database
    * User Name
    * Password
![image](https://user-images.githubusercontent.com/264750/41654370-255cd870-7481-11e8-8cd1-fa12b776216b.png)
* Click on `Test` to ensuring connection works, and then save:
![image](https://user-images.githubusercontent.com/264750/41654381-34cbafde-7481-11e8-9227-86d569ad922c.png)

**Comment by GrahamHewett** [comment]
You may need to run a different command for Step 2 on linux.
sudo service mongod start 
instead of just mongod
