### ISSUE TITLE
Fill the database with our TV shows

### ISSUE THREAD

**Issue by rmallols** [rmallols/kodflix#27]
All right, our `kodflix` database has been already created, but it's still obviously empty.

Please fill it by creating as many elements as TV shows we were already handling on the backend side.

**Comment by rmallols** [comment]
**Technical guidance:**

1. First, let's create a new `collection`, which is the equivalent of a `table` in the classic relational database world. We'll have `collection` for each type of data. For now, just create a new collection called `shows`
![image](https://user-images.githubusercontent.com/264750/41657081-0c15056e-748a-11e8-82ca-2319bfc2be0e.png)

2. Let's add some TV shows. Each entry of the `collection` is called `document`. As we had 6 TV shows registered, we'll add 6 `documents`
![image](https://user-images.githubusercontent.com/264750/41657123-3835e8de-748a-11e8-848e-d6aa502a36b2.png)

3. Look at the prompt we receive. It's asking us to enter a valid [JSON object](https://www.w3schools.com/js/js_json_intro.asp). On our backend side, we were already storing an array of JSON object, to this is as simply as copying&pasting each of them into individual `documents`
![image](https://user-images.githubusercontent.com/264750/41657243-a1a469da-748a-11e8-90de-243cc826055a.png)

4. Finally, you can show the list of added shows by just double clicking on the `shows` collection on the navigation panel.  Then you can:
* View added documents
* Edit them
* Delete them
![image](https://user-images.githubusercontent.com/264750/41657337-fd9fa7b8-748a-11e8-990e-d97e4078993e.png)

**Comment by tishayaem** [comment]
Instead of manually copy-pasting each tv show, you can do following:
1. In your terminal, navigate to the folder where you store file with tv shows array.
2.Edit your file, so you don't have anything apart from an array(no const or function).
3. Run this command: mongoimport --db kodflix --collection shows --type json --file nameOfYourFile.json --jsonArray
