### ISSUE TITLE
Play TV show trailers!

### ISSUE THREAD

**Issue by rmallols** [rmallols/kodflix#40]
Our company Director is super excited with the changes introduced on #39. Based on that, he's asked to go beyond by adding play capabilities for the trailers of each TV show.

![image](https://user-images.githubusercontent.com/264750/42047951-a64c1de6-7af9-11e8-887a-c1de8d633e00.png)

**Comment by rmallols** [comment]
**Technical guidance:**

1. Add a new route on `App.js`: `/:showId/play`, and bind it to a new `Play` component.

2. Define the behaviour of the `Play` component, which is reality would be very similar to the `Details` one as we'll have to get the TV show details based on its `Id`.

3. Add an [iframe](https://www.w3schools.com/tags/tag_iframe.asp) element to the `Play` component, with the `width` and `height` attributes set at `100%`. You can import videos from any source, e.g. [Youtube](https://www.w3schools.com/html/html_youtube.asp). Please figure out how to:

* Play the video automatically.
* Hide as much metadata as possible (to keep a nice, well-focused user experience).

4. As you've probably noticed already, each video will have a unique URL. We cannot trust our TV show `id`, as each video will have an external & different identifier. Hence, edit each document on the database (the local and remote ones) by adding a new `videoId` attribute. Finally, add that new `videoId` attribute to the video source to ensuring we always play the appropriate trailer video.

**Comment by justinliu6165** [comment]
I found that there are some issues with Chrome and autoplay, they have updated the policy

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

but muting it allows the autoplay to work. just fyi

**Comment by rmallols** [comment]
Yes they are changing the policies all the time - it gets just worse when talking about mobile & tablet devices :(.

Anyways, that's what it is! Autoplay is just a subtle detail, so please don't worry too much about it :)
