### ISSUE TITLE
Componentize the TV show element

### ISSUE THREAD

**Issue by rmallols** [rmallols/kodflix#7]
The new overlay introduced in #5 is great, users like it.

The mechanism, however, doesn't scale well, as we need to copy&paste it for each TV cover.

Transform the TV show element into a single component for scalability purposes.

**Comment by rmallols** [comment]
Hint: Managing components with React:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#importing-a-component

**Comment by SanjeQi** [comment]
#7 Componentize the TV show element #7
